### ISSUE TITLE
Prepare release of v2.0

### ISSUE THREAD

**Issue by lipkau** [AtlassianPS/ConfluencePS#43]
As the [v2.0 milestone](https://github.com/brianbunke/ConfluencePS/milestones) is nearly finished, some tasks are still open in order to release v2.0:
* [x] Update documentation
* [x] Update README
* [x] Version bump
* [ ] Merge `develop` into `master`
- [x] Create release notes
- [x] Add release notes to psd1

**Comment by lipkau** [comment]
@brianbunke 
**milestone**: v2.0
**assignee**: @brianbunke

**Comment by lipkau** [comment]
@brianbunke in case it helps, I created my task list of what I have to do before releasing a new version:
https://github.com/PSJira/PSJira/issues/126

**Comment by brianbunke** [comment]
Also:

- [ ] Create release notes
- [ ] Add release notes to psd1
