### ISSUE TITLE
Migrate Documentation to Markdown and External Help

### ISSUE THREAD

**Issue by lipkau** [AtlassianPS/ConfluencePS#67]
## Description
In order to have a documentation that is easier to access, easier to edit and maintain, and more flexible, we shall use [PlatyPS](https://github.com/PowerShell/platyPS) for the _help_ of the function.
_Discussion on this topic: https://github.com/AtlassianPS/AtlassianPS/issues/1_

## Task
* [x] Migrate all _Comment Based Help_ to `.md` files in `/docs`  
```posh
Import-Module MyAwesomeModule
New-MarkdownHelp -Module MyAwesomeModule -OutputFolder .\docs
```
* [x] Edit the `.md` files (`.EXAMPLE` block can have more that 1 command in it)
* [x] Create the `about_<module>`   
```posh
New-MarkdownAboutHelp -OutputFolder C:\Test -AboutName
```
* [x] Make AppVeyor generate the ExternalHelp file (.xml) when building  
```posh
New-ExternalHelp -Path ".\docs" -OutputPath "out\platyPS\en-US"
```
* [x] Remove the _Comment Based Help_ from all functions in the module
